"""Add platform column to games

Revision ID: 0acde696ce7e
Revises: 24086d1f7554
Create Date: 2026-09-25 11:25:30.345170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0acde696ce7e'
down_revision: Union[str, Sequence[str], None] = '24086d1f7554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('platform', sa.String(), nullable=False))
    op.add_column('games', sa.Column('status', sa.String(), nullable=True))
    op.add_column('games', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('games', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_games_external_id'), table_name='games')
    op.drop_index(op.f('ix_games_title'), table_name='games')
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    op.drop_column('games', 'cover_image')
    op.drop_column('games', 'external_id')
    op.drop_column('games', 'developer')
    op.drop_column('games', 'release_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('release_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('developer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_index(op.f('ix_games_title'), 'games', ['title'], unique=False)
    op.create_index(op.f('ix_games_external_id'), 'games', ['external_id'], unique=True)
    op.alter_column('games', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('games', 'user_id')
    op.drop_column('games', 'rating')
    op.drop_column('games', 'status')
    op.drop_column('games', 'platform')
    # ### end Alembic commands ###
